2018-03-12 22:27:05,973 ERROR: Exception on /socket.io/ [GET] [in /home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/a/git_local/path_chat/app/errors.py", line 7, in not_found_error
    return render_template('404.html'), 404
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/a/git_local/path_chat/app/templates/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/a/git_local/path_chat/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/a/git_local/path_chat/app/templates/base.html", line 23, in block "navbar"
    <li><a href="{{ url_for('chat') }}">{{ _('Chat') }}</a></li>
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'chat'. Did you mean 'chat.chat' instead?
2018-03-12 22:27:11,044 ERROR: Exception on /socket.io/ [GET] [in /home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/a/git_local/path_chat/app/errors.py", line 7, in not_found_error
    return render_template('404.html'), 404
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/a/git_local/path_chat/app/templates/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/a/git_local/path_chat/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/a/git_local/path_chat/app/templates/base.html", line 23, in block "navbar"
    <li><a href="{{ url_for('chat') }}">{{ _('Chat') }}</a></li>
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/a/.virtualenvs/flask_mega_tutorial/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'chat'. Did you mean 'chat.chat' instead?
