2018-02-13 18:57:00,797 ERROR: Exception on /change_password [POST] [in /home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jb/git_local/path_chat/app/routes.py", line 121, in change_password
    if form.validate_on_submit():
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/jb/git_local/path_chat/app/forms.py", line 68, in validate_current_password
    if not current_user.check_password(form.curret_password.data):
NameError: name 'form' is not defined
2018-02-13 18:58:15,560 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 18:58:27,926 ERROR: Exception on /change_password [POST] [in /home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jb/git_local/path_chat/app/routes.py", line 121, in change_password
    if form.validate_on_submit():
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/jb/git_local/path_chat/app/forms.py", line 68, in validate_current_password
    if not current_user.check_password(curret_password.data):
NameError: name 'curret_password' is not defined
2018-02-13 18:58:57,982 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 18:59:08,574 ERROR: Exception on /change_password [POST] [in /home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jb/git_local/path_chat/app/routes.py", line 121, in change_password
    if form.validate_on_submit():
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/jb/git_local/path_chat/app/forms.py", line 68, in validate_current_password
    if not current_user.check_password(form.current_password.data):
NameError: name 'form' is not defined
2018-02-13 18:59:37,006 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:02:12,727 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:05:01,066 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:11:00,452 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:11:50,489 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:12:31,914 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:13:41,190 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:18:37,939 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:19:09,154 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:19:29,054 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:21:12,754 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:21:37,159 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
2018-02-13 19:22:53,143 INFO: Microblog startup [in /home/jb/git_local/path_chat/app/__init__.py:52]
